POST http://localhost:3003/signup
Content-Type: application/json

{
    "name": "Lulu",
    "email":"lulu@gmail.com",
    "password":"123456",
    "role":"NORMAL"
}

###

POST http://localhost:3003/login
Content-Type: application/json

{
    "email":"lala1@gmail.com",
    "password":"123456"
}

###



